apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:  # these are replicaset labels
    app: app1
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:   # these are used to select the pod to create replicas
      app: app1
      tier: frontend
  #this is pod defination    
  template:
    metadata:
      labels:  # these are pod labels
        app: app1
        tier: frontend
    spec:
      containers:
      - name: app1
        image: gopichand9534/app1:v1

---
kind: Service
apiVersion: v1
metadata: 
  name: app1
spec:
  selector:
    app: app1
    tier: frontend
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port
  